site_name: CodeLite Documentation
site_url: https://www.codelite.org
repo_url: https://github.com/eranif/codelite
repo_name: GitHub
edit_uri: edit/master/docs/docs
nav:
  - Downloads:
      - Latest: downloads/download.md
      - Old Linux Repositories:
          - CodeLite 15.0: downloads/oldDownloads/Repositories15.md
          - CodeLite 14.0: downloads/oldDownloads/Repositories14.md
          - CodeLite 13.0: downloads/oldDownloads/Repositories13.md
          - CodeLite 12.0: downloads/oldDownloads/Repositories12.md
  - Getting started:
      - Prepare your environment:
          - Windows: getting_started/windows.md
          - Linux: getting_started/linux.md
          - macOS: getting_started/macos.md
      - Hello World: hello_world.md
  - Settings:
      - Look and feel: settings/colours_and_fonts.md
      - Keyboard shortcuts: settings/keyboard_shortcuts.md
      - Build Settings: settings/build_settings.md
      - Environment Variables: settings/environment_variables.md
      - Macros: /settings/macros
  - Workspace:
      - C/C++: workspaces/default.md
      - File System Workspace: workspaces/file_system.md
      - Remote File System Workspace: /plugins/remoty
      - PHP (via plugin): workspaces/php.md
      - Node.js (via plugin): workspaces/nodejs.md
  - Code Completion: code_completion/cxx.md
  - Plugins:
      - Language Server Protocol: plugins/lsp.md
      - Debug Adapter Client: plugins/dap.md
      - CMake: plugins/cmake.md
      - SFTP: plugins/sftp.md
      - SnipWiz: plugins/snipwiz.md
      - QMake: plugins/qmake.md
      - CppCheck: plugins/cppcheck.md
      - Subversion: plugins/svn.md
      - wxCrafter: plugins/wxcrafter.md
      - Git: plugins/git.md
      - UnitTest++: plugins/ut.md
      - Remoty: plugins/remoty.md
      - Rust: plugins/rust.md
      - Source Code Formatter: plugins/codeformatter.md
  - Debugging:
      - gdb: debuggers/gdb.md
      - Debug Adapter Client (dap): plugins/dap.md
      - XDebug (PHP): debuggers/xdebug.md
      - Node.js: debuggers/nodejs.md
      - Quick Debug: debuggers/quick_debug.md
  - Build:
      - wxWidgets: build/build_wx_widgets.md
      - CodeLite: build/build_from_sources.md
      - MinGW: build/mingw_builds.md
  - wxWidgets:
      - wxWidgets 3.1.5: wxWidgets/repo315.md
      - wxWidgets 3.1.6: wxWidgets/repo316.md
      - wxWidgets 3.1.7: wxWidgets/repo317.md
      - wxWidgets 3.2.0: wxWidgets/repo320.md
      - wxWidgets 3.2.1: wxWidgets/repo321.md
  - Misc:
      - Local Preferences: misc/local_preferences.md
      - Sync Project with File System: misc/reconcile_project.md
      - Bookmarks: misc/bookmarks.md
      - Undo & Redo: misc/ur.md
      - Tab Groups: misc/tabgroups.md
      - Tips & Tricks: misc/tips_and_tricks.md
      - Install Rust: misc/install_rust.md
  - Release Notes:
      - CodeLite v15.x - 16.0.0: release_notes/v16_0_0.md
      - CodeLite v16.x - 17.0.0: release_notes/v17_0_0.md
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  palette:
    scheme: default
    primary: black
  highlightjs: true
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - pymdownx.keys
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
